const supabase = require('../utils/supabase');
const xlsx = require('xlsx');
const whatsapp = require('../utils/whatsapp');


exports.recordAttendance = async (req, res) => {
    const { records, section } = req.body; // records: [{student_id, status}]
    const userId = req.user.id;
    const date = new Date().toISOString().split('T')[0];

    try {
        const formattedRecords = records.map(r => ({
            student_id: r.student_id,
            status: r.status,
            section: section,
            attendance_date: date,
            recorded_by: userId
        }));

        const { data, error } = await supabase
            .from('attendance_records')
            .upsert(formattedRecords, { onConflict: 'student_id,attendance_date' })
            .select('*, student:students(name, register_number)');

        if (error) throw error;

        // Trigger WhatsApp notification for absentees
        const absentees = data.filter(r => r.status === 'ABSENT');
        let whatsappUrl = null;

        if (absentees.length > 0) {
            // Internal automated notification
            await sendWhatsAppAlert(absentees, section, date);

            // Generate URL for client-side redirection
            const absenteeNames = absentees.map((a, i) => `${i + 1}. ${a.student?.name || 'Unknown Student'}`).join('\n');
            const messageText = `*Absentee List (${date})*\nSection: ${section}\n\nStudents:\n${absenteeNames}\n\n_Generated by ABI_`;
            
            // Format for WhatsApp Web/App redirect (using api.whatsapp.com/send for broader compatibility)
            whatsappUrl = `https://api.whatsapp.com/send?text=${encodeURIComponent(messageText)}`;
        }

        res.json({ 
            message: 'Attendance recorded successfully', 
            data,
            whatsappUrl // Return this so the frontend can redirect
        });
    } catch (err) {
        console.error('Error in recordAttendance:', err);
        res.status(500).json({ message: 'Error recording attendance', error: err.message });
    }
};

exports.getAnalytics = async (req, res) => {
    const { section, startDate, endDate } = req.query;
    try {
        let query = supabase.from('attendance_records').select('*, student:students(name)');
        if (section) query = query.eq('section', section);
        if (startDate) query = query.gte('attendance_date', startDate);
        if (endDate) query = query.lte('attendance_date', endDate);

        const { data, error } = await query;
        if (error) throw error;

        // Grouping logic for charts can go here or be handled by frontend
        res.json(data);
    } catch (err) {
        res.status(500).json({ message: 'Error fetching analytics', error: err.message });
    }
};

exports.downloadReport = async (req, res) => {
    const { section, startDate, endDate } = req.query;
    try {
        let query = supabase.from('attendance_records').select('attendance_date, status, section, student:students(name, register_number)');
        if (section) query = query.eq('section', section);
        if (startDate) query = query.gte('attendance_date', startDate);
        if (endDate) query = query.lte('attendance_date', endDate);

        const { data, error } = await query;
        if (error) throw error;

        const reportData = data.map(r => ({
            'Date': r.attendance_date,
            'Student Name': r.student.name,
            'Register No': r.student.register_number,
            'Section': r.section,
            'Status': r.status
        }));

        const workbook = xlsx.utils.book_new();
        const worksheet = xlsx.utils.json_to_sheet(reportData);
        xlsx.utils.book_append_sheet(workbook, worksheet, 'Attendance Report');

        const buffer = xlsx.write(workbook, { type: 'buffer', bookType: 'xlsx' });

        const safeSection = (section || 'All_Sections').replace(/[^a-zA-Z0-9]/g, '_');
        const fileName = `attendance report ${safeSection} ${startDate} to ${endDate}.xlsx`;

        res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        res.setHeader('Content-Disposition', `attachment; filename="${fileName}"`);
        res.send(buffer);
    } catch (err) {
        res.status(500).json({ message: 'Error generating report', error: err.message });
    }
};

async function sendWhatsAppAlert(absentees, section, date) {
    try {
        // Fetch specific recipient for this section
        const { data: settings } = await supabase
            .from('section_settings')
            .select('whatsapp_recipient')
            .eq('section_name', section)
            .single();

        const recipientId = settings?.whatsapp_recipient || process.env.WHATSAPP_RECIPIENT_ID;

        if (!recipientId || recipientId === 'WHATSAPP_GROUP_ID_OR_PHONE') {
            console.log(`WhatsApp recipient not configured for ${section}. Skipping notification.`);
            return;
        }

        const absenteeNames = absentees.map((a, i) => `${i + 1}. ${a.student.name}`).join('\n');
        const messageText = `*Absentee Alert (${date})*\nSection: ${section}\n\nStudents:\n${absenteeNames}\n\n_System generated by ABI_`;

        await whatsapp.sendMessage(section, recipientId, messageText);
        console.log(`WhatsApp alert triggered for ${section} via assigned client.`);
    } catch (err) {
        console.error('WhatsApp notification failed:', err.message);
    }
}
