const supabase = require('../utils/supabase');
const xlsx = require('xlsx');
// const whatsapp = require('../utils/whatsapp');


exports.recordAttendance = async (req, res) => {
    const { records, section } = req.body; // records: [{student_id, status}]
    const userId = req.user.id;
    const date = new Date().toISOString().split('T')[0];

    try {
        const formattedRecords = records.map(r => ({
            student_id: r.student_id,
            status: r.status,
            section: section,
            attendance_date: date,
            recorded_by: userId
        }));

        const { data, error } = await supabase
            .from('attendance_records')
            .upsert(formattedRecords, { onConflict: 'student_id,attendance_date' })
            .select('*, student:students(name, register_number)');

        if (error) throw error;

        // Trigger WhatsApp notification for absentees
        const absentees = records.filter(r => r.status === 'ABSENT');
        let whatsappUrl = null;

        if (absentees.length > 0) {
            // Re-fetch or use provided records to ensure we have names if possible
            // For the redirect URL, we can often rely on what the client sent if we include names there,
            // but here we'll try to use the returned data first, then fallback to IDs.
            
            const absenteeList = data ? data.filter(d => d.status === 'ABSENT') : [];
            const absenteeNames = absenteeList.length > 0 
                ? absenteeList.map((a, i) => `${i + 1}. ${a.student?.name || a.student_id}`).join('\n')
                : absentees.map((a, i) => `${i + 1}. Student ID: ${a.student_id}`).join('\n');

            const messageText = `*Absentee List (${date})*\nSection: ${section}\n\nStudents:\n${absenteeNames}\n\n_Generated by ABI_`;
            
            // Format for WhatsApp Web/App redirect
            whatsappUrl = `https://api.whatsapp.com/send?text=${encodeURIComponent(messageText)}`;
            
            // Optional: Internal automated notification (non-blocking)
            sendWhatsAppAlert(absenteeList.length > 0 ? absenteeList : absentees, section, date).catch(console.error);
        }

        res.json({ 
            message: 'Attendance recorded successfully', 
            count: records.length,
            absentees: absentees.length,
            whatsappUrl
        });
    } catch (err) {
        console.error('Error in recordAttendance:', err);
        res.status(500).json({ message: 'Error recording attendance', error: err.message });
    }
};

exports.getAnalytics = async (req, res) => {
    const { section, startDate, endDate } = req.query;
    try {
        let query = supabase.from('attendance_records').select('*, student:students(name, register_number)');
        if (section) query = query.eq('section', section);
        if (startDate) query = query.gte('attendance_date', startDate);
        if (endDate) query = query.lte('attendance_date', endDate);

        const { data, error } = await query;
        if (error) throw error;

        res.json(data || []);
    } catch (err) {
        res.status(500).json({ message: 'Error fetching analytics', error: err.message });
    }
};

exports.downloadReport = async (req, res) => {
    const { section, startDate, endDate } = req.query;
    try {
        let query = supabase.from('attendance_records').select('attendance_date, status, section, student:students(name, register_number)');
        if (section) query = query.eq('section', section);
        if (startDate) query = query.gte('attendance_date', startDate);
        if (endDate) query = query.lte('attendance_date', endDate);

        const { data, error } = await query;
        if (error) throw error;

        const reportData = data.map(r => ({
            'Date': r.attendance_date,
            'Student Name': r.student.name,
            'Register No': r.student.register_number,
            'Section': r.section,
            'Status': r.status
        }));

        const workbook = xlsx.utils.book_new();
        const worksheet = xlsx.utils.json_to_sheet(reportData);
        xlsx.utils.book_append_sheet(workbook, worksheet, 'Attendance Report');

        const buffer = xlsx.write(workbook, { type: 'buffer', bookType: 'xlsx' });

        const safeSection = (section || 'All_Sections').replace(/[^a-zA-Z0-9]/g, '_');
        const fileName = `attendance report ${safeSection} ${startDate} to ${endDate}.xlsx`;

        res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        res.setHeader('Content-Disposition', `attachment; filename="${fileName}"`);
        res.send(buffer);
    } catch (err) {
        res.status(500).json({ message: 'Error generating report', error: err.message });
    }
};

exports.exportOpenPyxl = async (req, res) => {
    const { section, startDate, endDate } = req.query;
    try {
        let query = supabase.from('attendance_records').select('attendance_date, status, section, student:students(name, register_number)');
        if (section) query = query.eq('section', section);
        if (startDate) query = query.gte('attendance_date', startDate);
        if (endDate) query = query.lte('attendance_date', endDate);

        const { data, error } = await query;
        if (error) throw error;

        // Handle empty data case - send minimal valid file
        const reportData = data && data.length > 0 ? data.map(r => ({
            'Date': r.attendance_date,
            'Student Name': r.student?.name || 'Unknown',
            'Register No': r.student?.register_number || 'N/A',
            'Section': r.section,
            'Status': r.status
        })) : [];

        const { spawn } = require('child_process');
        const path = require('path');
        const scriptPath = path.join(__dirname, '../../scripts/export_excel.py');

        const pythonProcess = spawn('python', [scriptPath]);

        const chunks = [];
        const errorChunks = [];

        pythonProcess.stdout.on('data', (data) => chunks.push(data));
        pythonProcess.stderr.on('data', (data) => errorChunks.push(data));

        pythonProcess.on('close', (code) => {
            if (code !== 0) {
                const errorMessage = Buffer.concat(errorChunks).toString();
                console.error('Python Error:', errorMessage);
                return res.status(500).json({ message: 'Error generating Excel file via Python', error: errorMessage });
            }

            const buffer = Buffer.concat(chunks);
            const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
            const fileName = `Class_Analytics_Export_${timestamp}.xlsx`;

            res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
            res.setHeader('Content-Disposition', `attachment; filename="${fileName}"`);
            res.send(buffer);
        });

        // Send JSON to Python stdin
        pythonProcess.stdin.write(JSON.stringify(reportData));
        pythonProcess.stdin.end();

    } catch (err) {
        console.error('Export OpenPyxl Error:', err);
        res.status(500).json({ message: 'Error fetching report data', error: err.message });
    }
};

async function sendWhatsAppAlert(absentees, section, date) {
    try {
        // Fetch specific recipient for this section
        const { data: settings } = await supabase
            .from('section_settings')
            .select('whatsapp_recipient')
            .eq('section_name', section)
            .single();

        const recipientId = settings?.whatsapp_recipient || process.env.WHATSAPP_RECIPIENT_ID;

        if (!recipientId || recipientId === 'WHATSAPP_GROUP_ID_OR_PHONE') {
            console.log(`WhatsApp recipient not configured for ${section}. Skipping notification.`);
            return;
        }

        const absenteeNames = absentees.map((a, i) => `${i + 1}. ${a.student.name}`).join('\n');
        const messageText = `*Absentee Alert (${date})*\nSection: ${section}\n\nStudents:\n${absenteeNames}\n\n_System generated by ABI_`;

        // await whatsapp.sendMessage(section, recipientId, messageText);
        console.log(`WhatsApp alert mock triggered for ${section} via assigned client.`);
    } catch (err) {
        console.error('WhatsApp notification failed:', err.message);
    }
}

exports.getStudentAttendance = async (req, res) => {
    const { id } = req.params;
    try {
        const { data: student, error: studentError } = await supabase
            .from('students')
            .select('id, name, register_number, section')
            .eq('id', id)
            .single();

        if (studentError) throw studentError;
        if (!student) return res.status(404).json({ message: 'Student not found' });

        const { data: attendance, error: attendanceError } = await supabase
            .from('attendance_records')
            .select('attendance_date, status')
            .eq('student_id', id)
            .order('attendance_date', { ascending: false });

        if (attendanceError) throw attendanceError;

        res.json({ student, attendance: attendance || [] });
    } catch (err) {
        res.status(500).json({ message: 'Error fetching student attendance', error: err.message });
    }
};

exports.exportIndividualOpenPyxl = async (req, res) => {
    const { id } = req.params;
    try {
        const { data: student, error: studentError } = await supabase
            .from('students')
            .select('*')
            .eq('id', id)
            .single();

        if (studentError) throw studentError;
        if (!student) return res.status(404).json({ message: 'Student not found' });

        const { data: attendance, error: attendanceError } = await supabase
            .from('attendance_records')
            .select('*')
            .eq('student_id', id)
            .order('attendance_date', { ascending: true });

        if (attendanceError) throw attendanceError;

        // Handle empty attendance data
        const reportData = attendance && attendance.length > 0 ? attendance.map(r => ({
            'Date': r.attendance_date,
            'Student Name': student.name,
            'Register No': student.register_number,
            'Section': r.section,
            'Status': r.status
        })) : [];

        const { spawn } = require('child_process');
        const path = require('path');
        const scriptPath = path.join(__dirname, '../../scripts/export_individual.py');

        const pythonProcess = spawn('python', [scriptPath]);

        const chunks = [];
        const errorChunks = [];

        pythonProcess.stdout.on('data', (data) => chunks.push(data));
        pythonProcess.stderr.on('data', (data) => errorChunks.push(data));

        pythonProcess.on('close', (code) => {
            if (code !== 0) {
                const errorMessage = Buffer.concat(errorChunks).toString();
                console.error('Python Error:', errorMessage);
                return res.status(500).json({ message: 'Error generating Individual Excel via Python', error: errorMessage });
            }

            const buffer = Buffer.concat(chunks);
            const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
            const safeName = student.name.replace(/[^a-zA-Z0-9]/g, '_');
            const fileName = `Student_${safeName}_Export_${timestamp}.xlsx`;

            res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
            res.setHeader('Content-Disposition', `attachment; filename="${fileName}"`);
            res.send(buffer);
        });

        pythonProcess.stdin.write(JSON.stringify(reportData));
        pythonProcess.stdin.end();

    } catch (err) {
        console.error('Export Individual OpenPyxl Error:', err);
        res.status(500).json({ message: 'Error fetching individual report data', error: err.message });
    }
};

